### ISSUE TITLE
[DOCS]: The PlaybackState property claims to be read only when it isn’t

### ISSUE THREAD

**Issue by VSCPlays** [RyanLua/Shime#8]
### Provide a description of requested docs changes

# The Issue
You can’t make properties read-only, yet it claims that the playback state property is read-only

## Part
> This Read-Only property

## More Details
https://devforum.roblox.com/t/2323033

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by RyanLua** [comment]
It is marked as read-only as to prevent people from thinking they can write to the property. The property is overwritten when the state updates again.

**Comment by VSCPlays** [comment]
Hmmmm,
